export default [
	'Zoltán Balázs [zoli]',
	'Lauren Bertolini',
	'István Bodnár [serif]',
	'Márton Borlay',
	'Steve Climaco',
	'Michelle Chiang',
	'Ernie Deeb',
	'Ashton Galloway-Taylor',
	'János Hardi',
	'Michael Scott Hertzberg [moimikey]',
	'László Heves',
	'Viktor Honti',
	'Etele Illés',
	'Zoltán Kalmár [kalmi]',
	'Balázs Kéki',
	'Olivér Kovács [zee]',
	'Dmitry Lambrianov',
	'Josh Laurito',
	'Mikhail Mitrofanov [migmit]',
	'Levente Molnar',
	'Kelly Monson',
	'Gergő Nagy [ngergo]',
	'Tamás Neltz',
	'Luca Németh',
	'Claire Neveu',
	'Ali Philippides',
	'Krisztián Pintér',
	'Balázs Pőcze [banyek]',
	'Ben Regenspan',
	'Grace Robertson',
	'Csaba Schreiner [edward]',
	'András Szatmári [strati]',
	'Péter Szász [eszpee] https://eszpee.kinja.com/',
	'Margaret Taormina',
	'Endre Ujhelyi',
	'Jim Bartus',
	'Gyorgy Bokros [hipra]',
	'Tibor Botos',
	'Long Cao',
	'Jeremy Chase',
	'Stuart Cheshire',
	'Dustin Curtis [dcurtis]',
	'Ian Fette',
	'Kevin Graham',
	'Kanwar Kultar Gill [kul]',
	'Matt Hamer',
	'Peter Hausel',
	'János Hegymegi [pv]',
	'Peri Hochwald',
	'Adam Homolya',
	'Stephen Kao',
	'József Kozma [joco]',
	'Gáspár Körtesi [gazs]',
	'Peter László',
	'Kyle Lucovsky',
	'Gábor Luk',
	'Eric Mittelhammer',
	'Ferenc Nehéz-Posony [pozsi]',
	'Diego Pineda',
	'Erin Pettigrew',
	'Tom Plunkett',
	'Justin Potter',
	'Chloe Powell',
	'Pedro Rodriguez',
	'Nandor Sivok [dominis]',
	'Julia Skrak',
	'Jessica Smith',
	'Casey Speer',
	'Jory Steifel',
	'Gergely Szabó',
	'Mikołaj Ziemowit Szabó',
	'Greg Takayama',
	'Alexandre Thomas [thomalexandre] https://athomas.me',
	'David Tobin',
	'Ferenc Tóth',
	'Ariel Viera'
];
