/* eslint-disable */
export default [
	{
		post_headline: 'Ride Out the Winter In Sherpa and Shearling-Lined Everything',
		post_shortExcerpt:
			'<p>Shearling lining is like the “perfect man” of menswear. It’s rugged and practical, yet soft and gentle at the same time. It’s stylish but versatile; not particularly committed to any trend or silhouette. You can put it in any situation, stand back and be like, “Damn, he’s a natural at this.”<br></p>',
		post_authorByline: 'Sherpa and Sherling',
		post_permalinkPath:
			'/ride-out-the-winter-in-sherpa-and-shearling-lined-every-1831468858?utm_source=dfpnative&utm_medium=homepage&utm_campaign=native_sherpasherling_ds',
		trackingPixel: '',
		headlineImage: {
			src: 'https://i.kinja-img.com/gawker-media/image/upload/wvym61kyx8vht0kremsu',
			isAnimated: false,
			id: 'wvym61kyx8vht0kremsu',
			width: 800,
			height: 450,
			format: 'jpg',
			frozenFormat: 'jpg',
			type: null
		},
		postId: 0,
		sponsored: 0,
		publishTime: {
			timestamp: 1546614000858,
			timezone: 'America/New_York',
			MdyHm: '01/04/2019 10:00',
			MdyatHm: '01/04/2019 at 10:00',
			rfc822: 'Fri, 04 Jan 2019 15:00:00 GMT',
			yMdHmsZ: '2019-01-04T10:00:00-05:00',
			hmma: '10:00am',
			day: 'Friday',
			Mddyyhmma: '1/04/19 10:00am',
			fullDate: 'January 4, 2019',
			relative: { amount: null, type: 'pastweek' }
		},
		version: 17,
		post_blogId: 0,
		blogAvatarUrl: '',
		postType: 'Native Ad',
		blogAvatar: '',
		blogDisplayName: 'The Inventory',
		blogCanonicalHost: 'theinventory.com',
		blogRecircGroup: '',
		blogBlogGroup: '',
		blogParentDisplayName: '',
		blogHideAuthorInfo: 0,
		clickthroughURL:
			'https://theinventory.com/ride-out-the-winter-in-sherpa-and-shearling-lined-every-1831468858%3Futm_source%3Ddfpnative%26utm_medium%3Dhomepage%26utm_campaign%3Dnative_sherpasherling_ds'
	},
	{
		post_headline: 'The 10 Best Deals of May 9, 2019',
		post_shortExcerpt: '<p>We see a lot of deals around the web over on <a href="https://kinjadeals.theinventory.com">Kinja Deals</a>, but these were our ten favorites today.<br></p>',
		post_authorByline: 'Ana Suarez',
		post_permalinkPath: '/the-10-best-deals-of-may-9-2019-1834651090',
		trackingPixel: '',
		headlineImage: {"src":"https://i.kinja-img.com/gawker-media/image/upload/yjhvvytlx8xsfjxl5e5i","isAnimated":true,"id":"yjhvvytlx8xsfjxl5e5i","width":800,"height":449,"format":"gif","frozenFormat":"jpg","type":null},
		postId: 1834651090,
		sponsored: 0,
		publishTime: {"timestamp":1557432900090,"timezone":"America/New_York","MdyHm":"05/09/2019 16:15","MdyatHm":"05/09/2019 at 16:15","rfc822":"Thu, 09 May 2019 20:15:00 GMT","yMdHmsZ":"2019-05-09T16:15:00-04:00",":hmma":"16:15pm","day":"Thursday","Mddyyhmma":"5/09/19 4:15pm","fullDate":"May 9, 2019","relative":{"amount":11,"type":"minutes"}},
		version: 17,
		post_blogId: 86286,
		blogAvatarUrl: '',
		postType: 'Native Ad',
		blogAvatar: {"id":"pvgisuoz9zuq8qv25x33","format":"png"},
		blogDisplayName: 'Kinja Deals',
		blogCanonicalHost: 'kinjadeals.theinventory.com',
		blogRecircGroup: 'partnerEditorial',
		blogBlogGroup: 'theinventory',
		blogParentDisplayName: 'The Inventory',
		blogHideAuthorInfo: 0,
		clickthroughURL: 'https://kinjadeals.theinventory.com/the-10-best-deals-of-may-9-2019-1834651090'

	},
	{
		post_headline: 'Save 25% On Your First Month Of Bespoke Post: Individually Curated Boxes For Guys',
		post_shortExcerpt:
			'<p><a href="http://gizmodomedia.go2cloud.org/aff_c?offer_id=168&amp;aff_id=2&amp;url_id=1883&amp;source=deadspin" target="_blank" rel="noopener"><strong>Bespoke Post</strong></a> is a subscription club for men delivering goods from small-batch brands in categories like barware, apparel, travel gear, and more. Simply take the lifestyle quiz and <a href="http://gizmodomedia.go2cloud.org/aff_c?offer_id=168&amp;aff_id=2&amp;url_id=1883&amp;source=deadspin" target="_blank" rel="noopener"><strong>Bespoke Post</strong></a> emails you on the 1st of each month with a full view of the box contents. Get <strong>25% off </strong>your first month, <strong>just $33.75</strong> with <strong>free</strong>…</p>',
		post_authorByline: 'Bespoke Post',
		post_permalinkPath: '/aff_c?offer_id=168&aff_id=2&url_id=1883&source=deadspin',
		trackingPixel: '',
		headlineImage: {
			src: 'https://i.kinja-img.com/gawker-media/image/upload/ygmdl9vikhunc3tmvxp3',
			isAnimated: false,
			id: 'ygmdl9vikhunc3tmvxp3',
			width: 800,
			height: 450,
			format: 'jpg',
			frozenFormat: 'jpg',
			type: null
		},
		postId: 0,
		sponsored: 1,
		publishTime: {
			timestamp: 1547675940178,
			timezone: 'America/New_York',
			MdyHm: '01/16/2019 16:59',
			MdyatHm: '01/16/2019 at 16:59',
			rfc822: 'Wed, 16 Jan 2019 21:59:00 GMT',
			yMdHmsZ: '2019-01-16T16:59:00-05:00',
			hmma: '16:59pm',
			day: 'Wednesday',
			Mddyyhmma: '1/16/19 4:59pm',
			fullDate: 'January 16, 2019',
			relative: { amount: 2, type: 'minutes' }
		},
		version: 17,
		post_blogId: 0,
		blogAvatarUrl: '',
		postType: '',
		blogAvatar: '',
		blogDisplayName: 'Bespoke Post',
		blogCanonicalHost: 'gizmodomedia.go2cloud.org',
		blogRecircGroup: '',
		blogBlogGroup: '',
		blogParentDisplayName: '',
		blogHideAuthorInfo: 0,
		clickthroughURL: 'http://gizmodomedia.go2cloud.org/aff_c%3Foffer_id%3D168%26aff_id%3D2%26url_id%3D1883%26source%3Ddeadspin'
	},
	{
		post_headline: 'The Climate Strike Movement Has Officially Gone Global',
		post_shortExcerpt:
			'<p>On Friday, students around the world woke up knowing that sometime between math, English, biology or some other rote class, they would stand up and walk out. From the tiny island of Vanuatu to Europe to the U.S., the climate strike movement is officially a global phenomenon. Up to a million students in 123 countries…</p>',
		post_authorByline: 'Brian Kahn',
		post_permalinkPath: '/the-climate-strike-movement-has-officially-gone-global-1833305314',
		trackingPixel: '',
		headlineImage: {
			src: 'https://i.kinja-img.com/gawker-media/image/upload/u30zzbs0g9cisxlm57og',
			isAnimated: false,
			id: 'u30zzbs0g9cisxlm57og',
			width: 800,
			height: 449,
			format: 'jpg',
			frozenFormat: 'jpg',
			type: null
		},
		postId: 1833305314,
		sponsored: 0,
		publishTime: {
			timestamp: 1552657500314,
			timezone: 'America/New_York',
			MdyHm: '03/15/2019 09:45',
			MdyatHm: '03/15/2019 at 09:45',
			rfc822: 'Fri, 15 Mar 2019 13:45:00 GMT',
			yMdHmsZ: '2019-03-15T09:45:00-04:00',
			hmma: '9:45am',
			day: 'Friday',
			Mddyyhmma: '3/15/19 9:45am',
			fullDate: 'March 15, 2019',
			relative: { amount: null, type: 'today' }
		},
		version: 17,
		post_blogId: 1636390014,
		blogAvatarUrl: '',
		postType: 'Native Ad',
		blogAvatar: { id: 'eir2ldhuj6n1thhxrcpq', format: 'png' },
		blogDisplayName: 'Earther',
		blogCanonicalHost: 'earther.gizmodo.com',
		blogRecircGroup: 'fmgNonSatire',
		blogBlogGroup: 'gizmodo',
		blogParentDisplayName: 'Gizmodo',
		blogHideAuthorInfo: 0,
		clickthroughURL: 'https://earther.gizmodo.com/the-climate-strike-movement-has-officially-gone-global-1833305314'
	},
	{
		post_headline: 'What’s Your Favorite RPG Memory from the ‘90s?',
		post_shortExcerpt:
			'<p>I vividly remember sitting on the top bunk of my buddy’s bunk bed the first time I heard about a role-playing game. Two years older than me, he had the wisdom and patience needed to explain that, no, these games couldn’t be played through in one run. I relish these early days of RPG gaming, where I focused my time on…</p>',
		post_authorByline: 'Giaco Furino for Another Eden',
		post_permalinkPath: '/what-s-your-favorite-rpg-memory-from-the-90s-1832160149',
		trackingPixel: '',
		headlineImage: {
			src: 'https://i.kinja-img.com/gawker-media/image/upload/stbksljjna1n9v0t2eoo',
			isAnimated: false,
			id: 'stbksljjna1n9v0t2eoo',
			width: 800,
			height: 450,
			format: 'png',
			frozenFormat: 'png',
			type: null
		},
		postId: 1832160149,
		sponsored: 1,
		publishTime: {
			timestamp: 1549987200149,
			timezone: 'America/New_York',
			MdyHm: '02/12/2019 11:00',
			MdyatHm: '02/12/2019 at 11:00',
			rfc822: 'Tue, 12 Feb 2019 16:00:00 GMT',
			yMdHmsZ: '2019-02-12T11:00:00-05:00',
			hmma: '11:00am',
			day: 'Tuesday',
			Mddyyhmma: '2/12/19 11:00am',
			fullDate: 'February 12, 2019',
			relative: { amount: null, type: 'greaterthanweek' }
		},
		version: 17,
		post_blogId: 4541888,
		blogAvatarUrl: '',
		postType: '',
		blogAvatar: { id: 'wfv9vswuhbtjxhiq3dgy', format: 'png' },
		blogDisplayName: 'studioatgizmodo',
		blogCanonicalHost: 'studioatgizmodo.kinja.com',
		blogRecircGroup: '',
		blogBlogGroup: 'studio',
		blogParentDisplayName: '',
		blogHideAuthorInfo: 0,
		clickthroughURL: 'https://studioatgizmodo.kinja.com/what-s-your-favorite-rpg-memory-from-the-90s-1832160149'
	},
	{
		post_headline: 'Report: More Women Forgoing Taking Their Husbands’ Names In Favor Of Something Badass Like Diesel',
		post_shortExcerpt:
			'<p>SANTA CRUZ, CA—A report published Friday by cultural anthropologists at the University of California, Santa Cruz, revealed that an increasing number of women are forgoing the custom of taking their husbands’ surnames and instead opting for something totally badass like Diesel, Nitro, or Pulverizer. “We’ve observed a…</p>',
		post_authorByline: 'onion edit test',
		post_permalinkPath: '/report-more-women-forgoing-taking-their-husbands-name-1833332576',
		trackingPixel: '',
		headlineImage: {
			src: 'https://i.kinja-img.com/gawker-media/image/upload/opzumcesido8h4lo0nk5',
			isAnimated: false,
			id: 'opzumcesido8h4lo0nk5',
			width: 800,
			height: 450,
			format: 'jpg',
			frozenFormat: 'jpg',
			type: null
		},
		postId: 1833332576,
		sponsored: 0,
		publishTime: {
			timestamp: 1552681140576,
			timezone: 'America/Chicago',
			MdyHm: '03/15/2019 15:19',
			MdyatHm: '03/15/2019 at 15:19',
			rfc822: 'Fri, 15 Mar 2019 20:19:00 GMT',
			yMdHmsZ: '2019-03-15T15:19:00-05:00',
			hmma: '15:19pm',
			day: 'Friday',
			Mddyyhmma: '3/15/19 3:19pm',
			fullDate: 'March 15, 2019',
			relative: { amount: null, type: 'today' }
		},
		version: 17,
		post_blogId: 1636079510,
		blogAvatarUrl: '',
		postType: 'Native Ad',
		blogAvatar: { id: 'eti2h1r4wg0bqxctxenl', format: 'png' },
		blogDisplayName: 'The Onion',
		blogCanonicalHost: 'www.theonion.com',
		blogRecircGroup: 'fmgSatire',
		blogBlogGroup: 'theonion',
		blogParentDisplayName: '',
		blogHideAuthorInfo: 1,
		clickthroughURL: 'https://www.theonion.com/report-more-women-forgoing-taking-their-husbands-name-1833332576'
	},
	{
		post_headline: 'Trumpet Player Wishes Someone Would Sound Horns For Him When He Entered Castle Gates For Once',
		post_shortExcerpt:
			'<p>EOFERWIC, BRITANNIA—Saying that it really wasn’t such a grandiose request after years of loyal servitude, Ilbert Hildebrondus, a local court trumpeter at the Old Baile Keep, confirmed Wednesday he wishes that, just once, someone would sound the horns for him as he entered the castle gates. “All I’m saying is that one…</p>',
		post_authorByline: 'Disenchantment TEST',
		post_permalinkPath: '/trumpet-player-wishes-someone-would-sound-horns-for-him-1828356887',
		trackingPixel: '',
		headlineImage: {
			src: 'https://i.kinja-img.com/gawker-media/image/upload/wndu3ahrvcm0lqne32ko',
			isAnimated: false,
			id: 'wndu3ahrvcm0lqne32ko',
			width: 800,
			height: 453,
			format: 'jpg',
			frozenFormat: 'jpg',
			type: null
		},
		postId: 1828356887,
		sponsored: 1,
		publishTime: {
			timestamp: 1534482300887,
			timezone: 'America/Chicago',
			MdyHm: '08/17/2018 00:05',
			MdyatHm: '08/17/2018 at 00:05',
			rfc822: 'Fri, 17 Aug 2018 05:05:00 GMT',
			yMdHmsZ: '2018-08-17T00:05:00-05:00',
			hmma: '0:05am',
			day: 'Friday',
			Mddyyhmma: '8/17/18 12:05am',
			fullDate: 'August 17, 2018',
			relative: { amount: null, type: 'greaterthanweek' }
		},
		version: 17,
		post_blogId: 1636079510,
		blogAvatarUrl: '',
		postType: '',
		blogAvatar: { id: 'eti2h1r4wg0bqxctxenl', format: 'png' },
		blogDisplayName: 'The Onion',
		blogCanonicalHost: 'www.theonion.com',
		blogRecircGroup: 'fmgSatire',
		blogBlogGroup: 'theonion',
		blogParentDisplayName: '',
		blogHideAuthorInfo: 1,
		clickthroughURL: 'https://www.theonion.com/trumpet-player-wishes-someone-would-sound-horns-for-him-1828356887'
	},
	{
		post_headline: 'WATCH: A Therapy Session Between Two Employees',
		post_shortExcerpt: '<p>When IT and Security don’t get along, it’s time to prescribe Okta.</p>',
		post_authorByline: 'Okta test',
		post_permalinkPath: '/watch-a-therapy-session-between-two-employees-1832623237',
		trackingPixel: '',
		headlineImage: {
			src: 'https://i.kinja-img.com/gawker-media/image/upload/puwkdf67iukuohcqvtpr',
			isAnimated: false,
			id: 'puwkdf67iukuohcqvtpr',
			width: 800,
			height: 450,
			format: 'jpg',
			frozenFormat: 'jpg',
			type: null
		},
		postId: 1832623237,
		sponsored: 1,
		publishTime: {
			timestamp: 1550162100237,
			timezone: 'America/New_York',
			MdyHm: '02/14/2019 11:35',
			MdyatHm: '02/14/2019 at 11:35',
			rfc822: 'Thu, 14 Feb 2019 16:35:00 GMT',
			yMdHmsZ: '2019-02-14T11:35:00-05:00',
			hmma: '11:35am',
			day: 'Thursday',
			Mddyyhmma: '2/14/19 11:35am',
			fullDate: 'February 14, 2019',
			relative: { amount: null, type: 'greaterthanweek' }
		},
		version: 17,
		post_blogId: 1636420981,
		blogAvatarUrl: '',
		postType: '',
		blogAvatar: '',
		blogDisplayName: 'Onion Native Content',
		blogCanonicalHost: 'onionnative.kinja.com',
		blogRecircGroup: '',
		blogBlogGroup: '',
		blogParentDisplayName: '',
		blogHideAuthorInfo: 0,
		clickthroughURL: 'https://onionnative.kinja.com/watch-a-therapy-session-between-two-employees-1832623237'
	}
];
