#!/usr/bin/env node

/*
 * Port of https://github.com/storybooks/storybook-deployer
 * With some modifications to push to a different repo
 */

const shell = require('shelljs');
const publishUtils = require('./utils/deployment');
const path = require('path');
const packageJson = require(path.resolve('./package.json'));

const OUTPUT_DIR = 'out' + Math.ceil(Math.random() * 9999);
const GIT_URL = 'git@github.com:gawkermedia/kinja-components.git';

// const absPath = path.resolve(OUTPUT_DIR);

// clear and re-create the out directory
shell.rm('-rf', OUTPUT_DIR);
shell.mkdir(OUTPUT_DIR);

// run our compile script
console.log('=> Building storybook');
// publishUtils.exec('npm run build-storybook -- -o ' + OUTPUT_DIR);
// publishUtils.exec('node ./node_modules/.bin/build-storybook -c .storybook - -o ' + absPath);
publishUtils.exec('node ./node_modules/.bin/build-storybook -s .public -c .storybook -o ' + OUTPUT_DIR);

// go to the out directory and create a *new* Git repo
shell.cd(OUTPUT_DIR);
publishUtils.exec('git init');

// inside this git repo we'll pretend to be a new user
publishUtils.exec('git config user.name "GH Pages Bot"');
publishUtils.exec('git config user.email "hello@ghbot.com"');
publishUtils.exec('git config commit.gpgsign false');

// The first and only commit to this new Git repo contains all the
// files present with the commit message "Deploy to GitHub Pages".
publishUtils.exec('git add .');
publishUtils.exec('git commit -m "Deploy Storybook to GitHub Pages"');

// Force push from the current repo's master branch to the remote
// repo's gh-pages branch. (All previous history on the gh-pages branch
// will be lost, since we are overwriting it.) We redirect any output to
// /dev/null to hide any sensitive credential data that might otherwise be exposed.
console.log('=> Deploying storybook');
publishUtils.exec('git push --force --quiet ' + GIT_URL + ' master:gh-pages')
shell.cd('..');
shell.rm('-rf', OUTPUT_DIR);

console.log();
console.log('=> Storybook deployed to: ' + publishUtils.getGHPagesUrl(GIT_URL));
